<a href="https://colab.research.google.com/github/khushwantsingh20/house_sales_prediction/blob/main/Linear_regression_multi_variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [ ]:
df=pd.read_csv("/content/homeprices_mltvrbl.csv")
df


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
import math
median_bedrooms= math.floor(df.bedrooms.median())
median_bedrooms

4

In [ ]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)


In [ ]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
reg= linear_model.LogisticRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
reg.coef_


array([[-2.49051256e-03,  1.62512833e-01,  4.50712047e-01],
       [ 1.46082517e-03,  8.50330763e-02, -1.70420643e-01],
       [-5.58847399e-03, -2.68383136e-01,  9.11684716e-01],
       [ 6.16310668e-04, -1.64817809e-02,  1.88791840e-02],
       [ 3.32761086e-03, -2.39675415e-01, -5.97026219e-01],
       [ 2.67423984e-03,  2.76994423e-01, -6.13829085e-01]])

In [ ]:
reg.intercept_

array([ 0.11005241,  0.03492731, -0.0815757 , -0.02568385, -0.01158097,
       -0.02613919])

In [ ]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([595000])